//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genetic_Genealogy_Kit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Genetic_Genealogy_Kit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap boy {
            get {
                object obj = ResourceManager.GetObject("boy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] diff {
            get {
                object obj = ResourceManager.GetObject("diff", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap disable {
            get {
                object obj = ResourceManager.GetObject("disable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap enable {
            get {
                object obj = ResourceManager.GetObject("enable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eraser {
            get {
                object obj = ResourceManager.GetObject("eraser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap father {
            get {
                object obj = ResourceManager.GetObject("father", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap girl {
            get {
                object obj = ResourceManager.GetObject("girl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] map_csv {
            get {
                object obj = ResourceManager.GetObject("map_csv", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mother {
            get {
                object obj = ResourceManager.GetObject("mother", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MT-HV2,57,372,316,CR:HVS2/HV2,Hypervariable segment 2 [classic:73-340 ]
        ///MT-OHR,110,441,332,CR:OH,H-strand origin
        ///MT-CSB1,213,235,23,CR:CSB1,Conserved sequence block 1
        ///MT-TFX,233,260,28,CR:TFX,mtTF1 binding site
        ///MT-TFY,276,303,28,CR:TFY,mtTF1 binding site
        ///MT-CSB2,299,315,17,CR:CSB2,Conserved sequence block 2
        ///MT-HPR,317,321,5,CR:HPR,replication primer
        ///MT-CSB3,346,363,18,CR:CSB3,Conserved sequence block 3
        ///MT-4H,371,379,9,CR:mt4H,mt4 H-strand control element
        ///MT-3H,384,391,8,CR:mt3H,mt3 H-strand control [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mtdna_map {
            get {
                return ResourceManager.GetString("mtdna_map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Node Id=&quot;mtDNAPhylogeny&quot;&gt;
        ///  &lt;Node Id=&quot;L0&quot; HG=&quot;G263A,C1048T,C3516a,T5442C,T6185C,C9042T,A9347G,G10589A,G12007A,A12720G&quot;&gt;
        ///    &lt;Node Id=&quot;L0a&apos;b&apos;f&apos;k&quot; HG=&quot;A189G,T4586C,C9818T,T16172C&quot;&gt;
        ///      &lt;Node Id=&quot;L0a&apos;b&apos;f&quot; HG=&quot;G73A,G185A,C195T,A263G!,A2245G,C5603T,A11641G,C15136T,G15431A&quot;&gt;
        ///        &lt;Node Id=&quot;L0a&apos;b&quot; HG=&quot;A93G,(A95c),T236C,C8428T,A8566G,G9755A,C16148T&quot;&gt;
        ///          &lt;Node Id=&quot;L0a&quot; HG=&quot;C146T,G5231A,G5460A,G11176A,T14308C,C16188g,T16278C,C16320T&quot;&gt;
        ///            &lt;Node Id=&quot;L0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mtDNAPhylogeny {
            get {
                return ResourceManager.GetString("mtDNAPhylogeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paste {
            get {
                object obj = ResourceManager.GetObject("paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RSRS {
            get {
                object obj = ResourceManager.GetObject("RSRS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AF4,AF5,AF6,L1284,AF7,AF8,AF9,AF10,AF13,L1086,L1087,L1088,L1091,L1092,L1094,L1096,L1097,L1102,L1103,L1104,L1106,L1107,L1108,L1109,L1110,L1111,L1113,L1114,L1115,L1117,L1119,L1122,L1126,L1131,L1133,L1134,L1138,L1139,L1140,L1141,L1144,L1146,L1147,L1148,L1151,L1152,L1154,L1156,L1157,L1158,L1159,L1160,L1161,L1163,L1233,L1234,L1236,AF3,L1085,L1089,L1090,L1093,L1095,L1098,L1099,L1101,L1105,L1116,L1118,L1120,L1121,L1123,L1124,L1125,L1127,L1128,L1129,L1130,L1132,L1135,L1136,L1137,L1142,L1143,L1145,L1150,L1155,L1235, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string snps_on_tree {
            get {
                return ResourceManager.GetString("snps_on_tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap world_map {
            get {
                object obj = ResourceManager.GetObject("world_map", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ysnp_hg19 {
            get {
                object obj = ResourceManager.GetObject("ysnp_hg19", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;HG name=&quot;Y-Adam&quot; markers=&quot;&quot;&gt;
        ///	&lt;HG name=&quot;A00&quot; markers=&quot;AF4,AF5,AF6/L1284,AF7,AF8,AF9,AF10,AF13,L1086,L1087,L1088,L1091,L1092,L1094,L1096,L1097,L1102,L1103,L1104,L1106,L1107,L1108,L1109,L1110,L1111,L1113,L1114,L1115,L1117,L1119,L1122,L1126,L1131,L1133,L1134,L1138,L1139,L1140,L1141,L1144,L1146,L1147,L1148,L1151,L1152,L1154,L1156,L1157,L1158,L1159,L1160,L1161,L1163,L1233,L1234,L1236&quot;/&gt;
        ///	&lt;HG name=&quot;A0-T&quot; markers=&quot;AF3,L1085,L1089,L1090,L1093,L1095,L1098,L1099,L1101,L1105,L [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ytree {
            get {
                return ResourceManager.GetString("ytree", resourceCulture);
            }
        }
    }
}
